from pathlib import Path
import json
import re

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]

SOURCE_DIR = ROOT / "bgs" / "source"
OUTPUT_DIR = ROOT / "bgs"
CONFIG_PATH = ROOT / "configs" / "backgrounds.json"


MAX_WIDTH = 2560
MAX_HEIGHT = 1600
QUALITY = 82

VALID_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".webp",
    ".tif",
    ".tiff",
}


def safe_name(path):
    name = path.stem.lower()
    name = re.sub(r"[^a-z0-9]+", "-", name)
    name = name.strip("-")

    return name or "background"


def optimize_image(source):
    output = OUTPUT_DIR / f"{safe_name(source)}.webp"

    with Image.open(source) as image:

        # Correct camera/EXIF rotation.
        image = ImageOps.exif_transpose(image)

        # Background images should be RGB.
        if image.mode in ("RGBA", "LA") or (
            image.mode == "P"
            and "transparency" in image.info
        ):
            background = Image.new(
                "RGB",
                image.size,
                (0, 0, 0),
            )

            rgba = image.convert("RGBA")

            background.paste(
                rgba,
                mask=rgba.getchannel("A"),
            )

            image = background

        else:
            image = image.convert("RGB")

        # Resize while preserving aspect ratio.
        image.thumbnail(
            (MAX_WIDTH, MAX_HEIGHT),
            Image.Resampling.LANCZOS,
        )

        # Save optimized WebP.
        image.save(
            output,
            "WEBP",
            quality=QUALITY,
            method=6,
        )

    print(
        f"Optimized: "
        f"{source.name} → "
        f"{output.name}"
    )

    return output


def main():

    SOURCE_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    source_files = sorted(
        file
        for file in SOURCE_DIR.rglob("*")
        if (
            file.is_file()
            and file.suffix.lower()
            in VALID_EXTENSIONS
        )
    )

    optimized_files = []

    for source in source_files:

        try:
            optimized = optimize_image(source)

            optimized_files.append(
                optimized
            )

        except Exception as error:

            print(
                f"WARNING: "
                f"Could not process "
                f"{source}: {error}"
            )

    # Regenerate the background config.
    config = {

        "_comment": (
            "AUTO-GENERATED by "
            "scripts/optimize_backgrounds.py. "
            "Add originals to bgs/source/."
        ),

        "changeEveryMs": 45000,

        "transitionDurationMs": 1800,

        "images": [

            f"./bgs/{image.name}"

            for image in optimized_files

        ],

    }

    CONFIG_PATH.write_text(
        json.dumps(
            config,
            indent=2,
        )
        + "\\n",

        encoding="utf-8",
    )

    print(
        f"Updated "
        f"{CONFIG_PATH.relative_to(ROOT)}"
    )

    print(
        f"{len(optimized_files)} "
        f"background(s) ready."
    )


if __name__ == "__main__":
    main()
